### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "tester",
  "email": "atester@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cminnie@test.com",
  "password": "password"
}

