### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "tester",
  "email": "atester@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cminnie@test.com",
  "password": "password"
}

### TUTORIALS INDEX
GET http://localhost:3000/tutorials
Content-Type: application/json

### TUTORIALS CREATE 
POST http://localhost:3000/tutorials
Content-Type: application/json

{
  "user_id": 2,
  "description": "Requests.http test desc.",
  "hyperlink": "https://tenor.com/bEF4U.gif" 
}

### RATINGS CREATE
POST http://localhost:3000/ratings
Content-Type: application/json