@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4NzM1ODJ9.fgrzBtI1ZGXYm4zBRgA8fct7Hs4vc0gqdvHkLGMPP9A
@host = http://localhost:3000

### USERS CREATE (SIGNUP)
POST http://localhost:3000/users
Content-Type: application/json

{
  "user_name": "tester",
  "email": "atester@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE (LOGIN)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cminnie@test.com",
  "password": "password"
}

### TUTORIALS INDEX
GET http://localhost:3000/tutorials
Content-Type: application/json

### TUTORIALS CREATE 
POST http://localhost:3000/tutorials
Content-Type: application/json

### TUTORIALS SHOW
GET http://localhost:3000/tutorials/1
Content-Type: application/json

{
  "user_id": 2,
  "description": "Requests.http test desc.",
  "hyperlink": "https://tenor.com/bEF4U.gif" 
}

# ### RATINGS INDEX
# GET http://localhost:3000/ratings
# Content-Type: application/json

### RATINGS CREATE
POST http://localhost:3000/ratings
Content-Type: application/json